# Generated by Django 5.2.16 on 2026-07-28 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('customer_type', models.CharField(choices=[('retail', 'خرده\u200cفروشی'), ('wholesale', 'عمده\u200cفروشی'), ('both', 'هردو')], default='retail', max_length=20, verbose_name='نوع مشتری')),
                ('is_wholesale_approved', models.BooleanField(default=False, help_text='فقط در صورت تأیید مدیر، امکان ثبت سفارش عمده دارد.', verbose_name='تأیید عمده\u200cفروشی')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای داخلی مدیر درباره این مشتری.', verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مشتری',
                'verbose_name_plural': 'پروفایل مشتری\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
