# Generated by Django 5.2.16 on 2026-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='اگر غیرفعال باشد کاربر نمی\u200cتواند وارد داشبورد شود - توسط مدیرکل کنترل می\u200cشود', verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر کل'), ('admin', 'ادمین فروشگاه'), ('visitor', 'ویزیتور'), ('customer', 'مشتری')], db_index=True, default='customer', help_text='manager=مدیرکل, admin=ادمین فروشگاه, visitor=ویزیتور, customer=مشتری', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_wholesale_approved',
            field=models.BooleanField(default=False, help_text='فقط در صورت تأیید مدیر، امکان ثبت سفارش عمده دارد و قیمت عمده می\u200cبیند.', verbose_name='تأیید عمده\u200cفروشی'),
        ),
    ]
