# Generated by Django 5.2.16 on 2026-07-22 16:31

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=orders.models.generate_order_number, editable=False, max_length=20, unique=True, verbose_name='شماره سفارش')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='آدرس تحویل')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات مشتری')),
                ('order_status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('CONFIRMED', 'تایید شده'), ('PREPARING', 'در حال آماده\u200cسازی'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش تک\u200cفروشی',
                'verbose_name_plural': 'سفارش\u200cهای تک\u200cفروشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(default=orders.models.generate_request_number, editable=False, max_length=20, unique=True, verbose_name='شماره درخواست')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام شرکت / فروشگاه')),
                ('contact_person', models.CharField(max_length=150, verbose_name='نام شخص رابط')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
                ('status', models.CharField(choices=[('NEW', 'درخواست جدید'), ('QUOTED', 'پیش\u200cفاکتور صادر شده'), ('CONVERTED', 'تبدیل به سفارش شده'), ('REJECTED', 'رد شده')], default='NEW', max_length=20, verbose_name='وضعیت درخواست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست خرید عمده',
                'verbose_name_plural': 'درخواست\u200cهای خرید عمده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد (لحظه سفارش)')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=100, unique=True, verbose_name='شناسه پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('payment_method', models.CharField(default='ONLINE', max_length=50, verbose_name='روش پرداخت')),
                ('payment_status', models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('REFUNDED', 'مسترد شده')], default='PENDING', max_length=20, verbose_name='وضعیت پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پیگیری تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد مورد نیاز')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات اختصاصی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_items', to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.wholesalerequest')),
            ],
            options={
                'verbose_name': 'آیتم درخواست عمده',
                'verbose_name_plural': 'آیتم\u200cهای درخواست عمده',
            },
        ),
    ]
