# Generated by Django 5.2.16 on 2026-09-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_options_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalerequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='به صورت خودکار از مجموع اقلام (تعداد × قیمت عمده محصول) محاسبه می\u200cشود', max_digits=12, verbose_name='مبلغ کل (تومان)'),
        ),
    ]
