# Generated by Django 5.2.16 on 2026-09-07 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_wholesalerequest_total_amount'),
        ('products', '0004_brand_brand_active_order_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='order_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orderitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orderitem_product_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payment_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', '-created_at'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalerequest',
            index=models.Index(fields=['user', '-created_at'], name='wholesale_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalerequest',
            index=models.Index(fields=['status', '-created_at'], name='wholesale_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalerequest',
            index=models.Index(fields=['phone'], name='wholesale_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalerequestitem',
            index=models.Index(fields=['request'], name='whitem_request_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalerequestitem',
            index=models.Index(fields=['product'], name='whitem_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='orderitem_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wholesalerequest',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='wholesale_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wholesalerequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='wholesaleitem_qty_positive'),
        ),
    ]
