# Generated by Django 5.2.16 on 2026-07-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='نام برند')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=50, verbose_name='کد محصول')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت با تخفیف (تومان)')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='بارکد')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('weight', models.PositiveIntegerField(default=1000, verbose_name='وزن (گرم)')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('pack', 'بسته'), ('piece', 'عدد'), ('carton', 'کارتن')], default='kg', max_length=20, verbose_name='واحد')),
                ('tag', models.CharField(blank=True, choices=[('', 'بدون برچسب'), ('new', 'جدید'), ('best', 'پرفروش'), ('discount', 'تخفیف'), ('special', 'ویژه')], max_length=20, verbose_name='برچسب ویژه')),
                ('badge', models.CharField(blank=True, choices=[('', 'بدون نشان'), ('fresh', 'تازه'), ('hot', 'محبوب'), ('premium', 'پریمیوم')], max_length=20, verbose_name='نشان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده')], default='published', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('available', models.BooleanField(default=True, verbose_name='موجود است')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['order', 'name'],
            },
        ),
    ]
