# Generated by Django 5.2.16 on 2026-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('pack', 'بسته'), ('piece', 'عدد'), ('carton', 'کارتن')], default='pack', help_text='واحد برای فروش جزئی - مثلاً بسته، عدد', max_length=20, verbose_name='واحد خرده\u200cفروشی'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_min_quantity',
            field=models.PositiveIntegerField(default=10, help_text='حداقل تعداد/وزن برای سفارش عمده - توسط مدیرکل یا ادمین تعیین می\u200cشود', verbose_name='حداقل مقدار عمده'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('pack', 'بسته'), ('piece', 'عدد'), ('carton', 'کارتن')], default='kg', help_text='واحد برای فروش عمده - مثلاً کیلوگرم، کارتن', max_length=20, verbose_name='واحد عمده\u200cفروشی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('pack', 'بسته'), ('piece', 'عدد'), ('carton', 'کارتن')], default='pack', max_length=20, verbose_name='واحد (قدیمی - برای سازگاری)'),
        ),
    ]
