# Generated by Django 5.2.16 on 2026-08-04 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_payment_options_order_user_and_more'),
        ('products', '0002_alter_category_options_category_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ دریافتی')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارتخوان سیار'), ('cheque', 'چک'), ('online', 'آنلاین')], default='cash', max_length=20, verbose_name='نوع پرداخت')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='شماره رسید')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ دریافت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to='orders.order', verbose_name='سفارش مرتبط (اختیاری)')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collections', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده (ویزیتور/ادمین)')),
            ],
            options={
                'verbose_name': 'دریافت وجه نقد',
                'verbose_name_plural': 'دریافت\u200cهای وجه نقد',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='درصد پورسانت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پورسانت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت پورسانت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order', verbose_name='سفارش')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='ویزیتور')),
            ],
            options={
                'verbose_name': 'پورسانت',
                'verbose_name_plural': 'پورسانت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='کل بدهی')),
                ('total_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='کل پرداختی')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین سفارش')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین پرداخت')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='معوقه؟')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_profile', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'بدهی مشتری',
                'verbose_name_plural': 'بدهی مشتریان',
                'ordering': ['-total_debt'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=0, help_text='قیمت برای مشتری عادی', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه (جزئی)')),
                ('wholesale_price', models.DecimalField(decimal_places=0, help_text='قیمت برای مشتری تایید شده عمده', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت عمده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pricing', to='products.product', verbose_name='محصول')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'قیمت\u200cگذاری محصول',
                'verbose_name_plural': 'قیمت\u200cگذاری محصولات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ بازدید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بازدید'), ('visited', 'بازدید شده'), ('ordered', 'سفارش ثبت شده'), ('no_order', 'سفارش نداشت'), ('postponed', 'به تعویق افتاد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('priority', models.PositiveIntegerField(default=1, help_text='1=بالا, 5=پایین', verbose_name='اولویت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت ویزیتور')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'customer_profile__role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='visits_received', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('visitor', models.ForeignKey(limit_choices_to={'customer_profile__role': 'visitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='visit_schedules', to=settings.AUTH_USER_MODEL, verbose_name='ویزیتور')),
            ],
            options={
                'verbose_name': 'برنامه بازدید',
                'verbose_name_plural': 'برنامه\u200cهای بازدید',
                'ordering': ['date', 'priority'],
                'unique_together': {('visitor', 'customer', 'date')},
            },
        ),
    ]
