# Generated by Django 5.2.16 on 2026-09-03 13:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداختی')),
                ('commission_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پورسانت')),
                ('reference_number', models.CharField(blank=True, max_length=80, verbose_name='شماره رسید / پیگیری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commissions', models.ManyToManyField(blank=True, related_name='payment_batches', to='dashboard.commission', verbose_name='پورسانت\u200cها')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments_done', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to=settings.AUTH_USER_MODEL, verbose_name='ویزیتور')),
            ],
            options={
                'verbose_name': 'پرداخت پورسانت',
                'verbose_name_plural': 'پرداخت\u200cهای پورسانت',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='درصد پورسانت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rule_updates', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
                ('visitor', models.OneToOneField(limit_choices_to={'customer_profile__role': 'visitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule', to=settings.AUTH_USER_MODEL, verbose_name='ویزیتور')),
            ],
            options={
                'verbose_name': 'قانون پورسانت',
                'verbose_name_plural': 'قوانین پورسانت',
                'ordering': ['visitor__username'],
            },
        ),
    ]
