# Generated by Django 5.2.16 on 2026-09-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_commissionpayment_commissionrule'),
        ('orders', '0003_wholesalerequest_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='wholesale_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.wholesalerequest', verbose_name='درخواست عمده'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='orders.order', verbose_name='سفارش خرده'),
        ),
    ]
